### ISSUE TITLE
User: Dashboard home - UI

### ISSUE THREAD

**Issue by dabsclement** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#16]
- Develop the User Dashboard pages UI appropriately
- The user dashboard home contains 5 pages ( you should send a pull request for each of the pages)
- Ensure they are responsive and follow the responsive design on the Figma
- Implement images properly
- Follow the colour guide and the appropriate colours

**Comment by Temilola007** [comment]
Hi. Can I work on this as well?

**Comment by PraiseDelia** [comment]
The admin said one person per issue but you can still check with him if that's okay.

**Comment by maziigwe** [comment]
what's the status of this issue? No, pull request yet. It's blocking other Dashboard features. Assign it to me, if possible.

**Comment by PraiseDelia** [comment]
> what's the status of this issue? No, pull request yet. It's blocking other Dashboard features. Assign it to me, if possible.
I'm on it.
I'll make a pull request tomorrow.

**Comment by maziigwe** [comment]
Hi @PraiseDelia, any update yet?

**Comment by ogoo-x** [comment]
@PraiseDelia Hi. I'd love to work on the dashboard products popup. Are you done with the issue yet?

**Comment by PraiseDelia** [comment]
Hi @dabsclement.
I am done implementing the dashboard feature, however, I don't think I can make any further progress due to the other contributors not sticking to the contribution guideline.
The file structure is unlike the typical React project. Attached is a screenshot of the current state of the directory structure.
![Screenshot (197)](https://user-images.githubusercontent.com/65369099/194850914-095a8c3d-ea72-4950-a06b-74c59201c93c.png)

**Comment by Osilaja78** [comment]
Any update on this issue please?

**Comment by ingressive4good** [comment]
the issue has been assigned to you @Osilaja78

**Comment by Osilaja78** [comment]
Alright @ingressive4good

**Comment by ingressive4good** [comment]
@Osilaja78 what is the progress status of this?

**Comment by Osilaja78** [comment]
More than halfway through, was delayed due to the new folder structure which caused a lot of import errors.  Will make a PR soon @ingressive4good
