### ISSUE TITLE
Authentication: Verification Sucessful:UI

### ISSUE THREAD

**Issue by ingressive4good** [Ingressive-for-Good/I4G-OPENSOURCE-FRONTEND-PROJECT-2022#5]
- Develop the verification successful page UI appropriately
- Ensure they are responsive and follow the responsive design on the figma
- Implement images properly
- Follow the color guide and the appropriate colors

**Comment by scarnation** [comment]
would love to get on this soon as =I get edit access on figma

**Comment by dprincecoder** [comment]
@scarnation are you working on this?

**Comment by scarnation** [comment]
If you want to proceed working on this then that would be great, since I am currently working on the ux with the designers and would just get back on the Frontend when I am done with my design tasks then. Might just share the components to you if you need them. I tested a modal on another screen earlier but didn't push so just proceed then

**Comment by dprincecoder** [comment]
Alright ✅ 
Let me take it
